#!/usr/bin/env bash

# Get the current script directory in a safe way
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

OUTPUT_FILE="$SCRIPT_DIR/brew_backup.sh"

echo "#!/usr/bin/env bash" > "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "# This file was generated by $0 on $(date)" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "# Formulae" >> "$OUTPUT_FILE"
# Get all formulae
formulae=$(brew list --formula)
echo "brew install \\" >> "$OUTPUT_FILE"
# Process formulae
count=0
total=$(echo "$formulae" | wc -w | tr -d ' ')
for formula in $formulae; do
  count=$((count + 1))
  if [ $count -eq $total ]; then
    # Last item, no backslash
    echo "    $formula" >> "$OUTPUT_FILE"
  else
    # Not the last item, add backslash
    echo "    $formula \\" >> "$OUTPUT_FILE"
  fi
done
echo "" >> "$OUTPUT_FILE"
echo "# Casks" >> "$OUTPUT_FILE"
# Get all casks
casks=$(brew list --cask)
echo "brew install --cask \\" >> "$OUTPUT_FILE"
# Process casks
count=0
total=$(echo "$casks" | wc -w | tr -d ' ')
for cask in $casks; do
  count=$((count + 1))
  if [ $count -eq $total ]; then
    # Last item, no backslash
    echo "    $cask" >> "$OUTPUT_FILE"
  else
    # Not the last item, add backslash
    echo "    $cask \\" >> "$OUTPUT_FILE"
  fi
done
chmod +x "$OUTPUT_FILE"
