#!/usr/bin/env bash

# This file was generated by ./backup-brew-formulae.sh on Sun 18 May 2025 14:42:54 BST

# Formulae
brew install \
    ca-certificates \
    cocoapods \
    fasttext \
    handbrake \
    libyaml \
    ollama \
    oniguruma \
    openssl@3 \
    podman \
    ruby

# Casks
brew install --cask \
    1password \
    1password-cli \
    arduino-ide \
    balenaetcher \
    elgato-control-center \
    ente-auth \
    insta360-studio \
    iterm2 \
    jetbrains-toolbox \
    kap \
    logi-options+ \
    nordvpn \
    notion \
    obs \
    obsidian \
    plex \
    podman-desktop \
    proton-mail \
    raycast \
    slack \
    spotify \
    steam \
    telegram \
    visual-studio-code \
    vlc \
    whatsapp \
    zed \
    zotero
